spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/gymroster"
    username: "postgres"
    password: "gympass"
  jpa:
    show-sql: false

app:
  cors:
    allowed-origins: http://localhost:3001,http://localhost:3000
