spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/gymroster"
    username: "postgres"
    password: "gympass"
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        jdbc: "DEBUG"