CREATE TABLE athlete (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(40) NOT NULL,
    home_city VARCHAR(50) NOT NULL,
    home_state_code VARCHAR(2),
    home_country_code VARCHAR(3),
    club_name VARCHAR(100),
    creation_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_update_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_athlete UNIQUE (first_name, last_name, home_city)
);

CREATE TABLE athlete_roster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_year SMALLINT NOT NULL,
    athlete_id BIGINT NOT NULL,
    college_id BIGINT NOT NULL,
    academic_year_code VARCHAR(20) NOT NULL,
    events VARCHAR(20),
    creation_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_update_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_athlete_roster UNIQUE (season_year, college_id, athlete_id)
);

CREATE TABLE coach (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(40) NOT NULL,
    creation_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_update_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_coach UNIQUE (first_name, last_name)
);

CREATE TABLE coach_roster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_year SMALLINT NOT NULL,
    coach_id BIGINT NOT NULL,
    college_id BIGINT NOT NULL,
    role_code VARCHAR(20) NOT NULL,
    creation_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_update_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_coach_roster UNIQUE (season_year, college_id, coach_id)
);

CREATE TABLE college (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     code_name VARCHAR(20) NOT NULL,
     short_name VARCHAR(30) NOT NULL,
     long_name VARCHAR(100) NOT NULL,
     nickname VARCHAR(20),
     conference_code VARCHAR(20) NOT NULL,
     division_code VARCHAR(20) NOT NULL,
     region_code VARCHAR(20) NOT NULL,
     state_code VARCHAR(2) NOT NULL,
     city VARCHAR(50) NOT NULL,
     team_url VARCHAR(255),
     creation_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
     last_update_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
     CONSTRAINT uk_college UNIQUE (code_name)
);

alter table if exists athlete_roster add constraint fk_athlete_roster_athlete foreign key (athlete_id) references athlete;
alter table if exists athlete_roster add constraint fk_athlete_roster_college foreign key (college_id) references college;
alter table if exists coach_roster add constraint fk_coach_roster_coach foreign key (coach_id) references coach;
alter table if exists coach_roster add constraint fk_coach_roster_college foreign key (college_id) references college;
