CREATE TABLE meet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_date DATE NOT NULL,
    event_name VARCHAR(200) NOT NULL,
    location VARCHAR(100),
    creation_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_update_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_meet UNIQUE (event_date, event_name),
);

CREATE TABLE meet_score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meet_id BIGINT NOT NULL,
    athlete_roster_id BIGINT NOT NULL,
    event_code VARCHAR(20) NOT NULL,
    rotation INTEGER,
    start_order INTEGER,
    final_score DOUBLE PRECISION NOT NULL,
    difficulty_score DOUBLE PRECISION,
    execution_score DOUBLE PRECISION,
    neutral_deduction DOUBLE PRECISION,
    bonus_points DOUBLE PRECISION,
    has_score_inquiry BOOLEAN NOT NULL DEFAULT FALSE,
    is_score_edited BOOLEAN NOT NULL DEFAULT FALSE,
    score_details JSONB,
    creation_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_update_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_meet_score UNIQUE (meet_id, athlete_roster_id, event_code),
    CONSTRAINT fk_meet_score_meet FOREIGN KEY (meet_id) REFERENCES meet,
    CONSTRAINT fk_meet_score_athlete_roster FOREIGN KEY (athlete_roster_id) REFERENCES athlete_roster
);